name: "Main: Run"
on:
  workflow_dispatch: {}
  push:
    branches:
      - "aws-main"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
