name: "WF: run"

on:
  workflow_run:
    workflows: ["Main: Run"]
    types: [completed]
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy: PR branch to AWS"
        uses: actions/checkout@v6
      
